/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Password */
        post: operations["set_password_api_v1_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available Providers */
        get: operations["available_providers_api_v1_auth_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connections */
        get: operations["connections_api_v1_auth_connections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Password Status */
        get: operations["password_status_api_v1_auth_password_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Redirect */
        get: operations["start_redirect_api_v1_auth_oauth__provider__start_get"];
        put?: never;
        /** Start */
        post: operations["start_api_v1_auth_oauth__provider__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback */
        get: operations["callback_api_v1_auth_oauth__provider__callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ventures */
        get: operations["ventures_api_v1_ventures_get"];
        put?: never;
        /** Create Venture */
        post: operations["create_venture_api_v1_ventures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/passport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Passport */
        get: operations["get_passport_api_v1_ventures__venture_id__passport_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/hypotheses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Hypotheses */
        get: operations["list_hypotheses_api_v1_ventures__venture_id__hypotheses_get"];
        put?: never;
        /** Add Hypothesis */
        post: operations["add_hypothesis_api_v1_ventures__venture_id__hypotheses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/intake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit Concept */
        post: operations["edit_concept_api_v1_ventures__venture_id__intake_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture */
        post: operations["capture_api_v1_ventures__venture_id__evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/evidence/{receipt_id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw */
        post: operations["withdraw_api_v1_ventures__venture_id__evidence__receipt_id__withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Artifact */
        post: operations["artifact_api_v1_ventures__venture_id__artifacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock Experiment */
        post: operations["lock_experiment_api_v1_ventures__venture_id__experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/experiments/{experiment_id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Observe */
        post: operations["observe_api_v1_ventures__venture_id__experiments__experiment_id__observations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_api_v1_ventures__venture_id__decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue */
        post: operations["enqueue_api_v1_ventures__venture_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agents */
        get: operations["agents_api_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Pipeline */
        post: operations["create_pipeline_api_v1_ventures__venture_id__pipelines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/agent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue */
        post: operations["enqueue_api_v1_ventures__venture_id__agent_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/agent-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_ventures__venture_id__agent_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/agent-runs/{run_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review */
        post: operations["review_api_v1_ventures__venture_id__agent_runs__run_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/agent-runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_ventures__venture_id__agent_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/research/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Saved */
        get: operations["search_saved_api_v1_ventures__venture_id__research_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/research/read-file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read File */
        post: operations["read_file_api_v1_ventures__venture_id__research_read_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/research/read-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read Source */
        post: operations["read_source_api_v1_ventures__venture_id__research_read_source_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/research/web-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Web */
        post: operations["search_web_api_v1_ventures__venture_id__research_web_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/mvp-exports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_v1_ventures__venture_id__mvp_exports_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ventures/{venture_id}/mvp-exports/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Download */
        post: operations["download_api_v1_ventures__venture_id__mvp_exports_download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityView */
        ActivityView: {
            /** Id */
            id: string;
            /** Event Type */
            event_type: string;
            /** Description */
            description: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AgentRequest */
        AgentRequest: {
            /** Expected Revision */
            expected_revision: number;
            /**
             * Agent Id
             * @enum {string}
             */
            agent_id: "home" | "research" | "market" | "customer" | "competitor" | "model" | "finance" | "experiment" | "simulation" | "academy" | "ecosystem" | "investor" | "passport";
            /** Objective */
            objective: string;
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** Evidence Ids */
            evidence_ids?: string[];
            /** Artifact Ids */
            artifact_ids?: string[];
            /** Experiment Ids */
            experiment_ids?: string[];
            /** Stage Id */
            stage_id?: string | null;
            /** Supersedes Artifact Id */
            supersedes_artifact_id?: string | null;
            /**
             * Mode
             * @default AUTO
             * @enum {string}
             */
            mode: "AUTO" | "RULE" | "MODEL";
            /**
             * Allow Model Processing
             * @default false
             */
            allow_model_processing: boolean;
            /**
             * Data Policy
             * @default cloud_allowed
             * @enum {string}
             */
            data_policy: "cloud_allowed" | "local_only";
            /** Preferred Profile */
            preferred_profile?: string | null;
            budget?: components["schemas"]["Budget"];
            /**
             * External Actions
             * @default false
             * @constant
             */
            external_actions: false;
        };
        /** AgentReview */
        AgentReview: {
            /** Expected Revision */
            expected_revision: number;
            /**
             * Choice
             * @enum {string}
             */
            choice: "accept" | "reject";
            /** Rationale */
            rationale: string;
            /** Expected Result Hash */
            expected_result_hash: string;
        };
        /** ArtifactCreate */
        ArtifactCreate: {
            /** Expected Revision */
            expected_revision: number;
            /**
             * Capability
             * @enum {string}
             */
            capability: "market" | "finance" | "simulation" | "model" | "competitor" | "academy" | "ecosystem" | "investor";
            /** Title */
            title: string;
            /** Inputs */
            inputs: {
                [key: string]: unknown;
            };
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** AuthorizationView */
        AuthorizationView: {
            /** Authorization Url */
            authorization_url: string;
        };
        /** Budget */
        Budget: {
            /**
             * Max Steps
             * @default 12
             */
            max_steps: number;
            /**
             * Max Seconds
             * @default 60
             */
            max_seconds: number;
            /**
             * Max Cost Inr
             * @default 0
             */
            max_cost_inr: number;
        };
        /** Command */
        Command: {
            /** Expected Revision */
            expected_revision: number;
        };
        /** ConceptUpdate */
        ConceptUpdate: {
            /** Expected Revision */
            expected_revision: number;
            /** Name */
            name: string;
            /** Idea */
            idea: string;
            /** Customer Segment */
            customer_segment: string;
            /** Geography */
            geography: string;
        };
        /** DecisionCreate */
        DecisionCreate: {
            /** Expected Revision */
            expected_revision: number;
            /**
             * Target Type
             * @enum {string}
             */
            target_type: "experiment" | "artifact" | "run";
            /** Target Id */
            target_id: string;
            /**
             * Choice
             * @enum {string}
             */
            choice: "continue" | "revise" | "stop" | "accept" | "reject";
            /** Rationale */
            rationale: string;
        };
        /** ExperimentCreate */
        ExperimentCreate: {
            /** Expected Revision */
            expected_revision: number;
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Title */
            title: string;
            protocol: components["schemas"]["Protocol"];
        };
        /** ExportApproval */
        ExportApproval: {
            /** Artifact Ids */
            artifact_ids: string[];
            /** Purpose */
            purpose: string;
            /** Preview Hash */
            preview_hash: string;
            /**
             * Format
             * @enum {string}
             */
            format: "pdf" | "docx" | "csv" | "json";
            /**
             * Approved
             * @constant
             */
            approved: true;
        };
        /** ExportSelection */
        ExportSelection: {
            /** Artifact Ids */
            artifact_ids: string[];
            /** Purpose */
            purpose: string;
        };
        /** FileRead */
        FileRead: {
            /** Filename */
            filename: string;
            /** Content Base64 */
            content_base64: string;
        };
        /** FounderView */
        FounderView: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Onboarding Completed */
            onboarding_completed: boolean;
            /** Has Password */
            has_password: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at?: string | null;
            /**
             * Realm
             * @default product
             * @constant
             */
            realm: "product";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HypothesisCreate */
        HypothesisCreate: {
            /** Statement */
            statement: string;
            /**
             * Category
             * @default problem
             * @enum {string}
             */
            category: "problem" | "customer" | "pricing" | "solution";
            /** Expected Revision */
            expected_revision: number;
        };
        /** HypothesisView */
        HypothesisView: {
            /** Id */
            id: string;
            /** Statement */
            statement: string;
            /** Category */
            category: string;
            /**
             * Status
             * @constant
             */
            status: "unvalidated";
            /**
             * Origin
             * @constant
             */
            origin: "founder_asserted";
            /** Revision */
            revision: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Login */
        Login: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** OAuthStart */
        OAuthStart: {
            /**
             * Mode
             * @default sign_in
             * @enum {string}
             */
            mode: "sign_in" | "connect";
        };
        /** ObservationCreate */
        ObservationCreate: {
            /** Expected Revision */
            expected_revision: number;
            /** Participant Code */
            participant_code: string;
            /** Receipt Id */
            receipt_id: string;
            /** Success */
            success: boolean;
            /**
             * Instrument Valid
             * @default true
             */
            instrument_valid: boolean;
            /**
             * Deviation
             * @default
             */
            deviation: string;
        };
        /** Passport */
        Passport: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Realm
             * @default product
             * @constant
             */
            realm: "product";
            venture: components["schemas"]["VentureView"];
            /** Hypotheses */
            hypotheses: components["schemas"]["HypothesisView"][];
            /** Activity */
            activity: components["schemas"]["ActivityView"][];
            /**
             * Evidence Count
             * @default 0
             */
            evidence_count: number;
            /**
             * Decision Count
             * @default 0
             */
            decision_count: number;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            }[];
            /** Artifacts */
            artifacts?: {
                [key: string]: unknown;
            }[];
            /** Experiments */
            experiments?: {
                [key: string]: unknown;
            }[];
            /** Decisions */
            decisions?: {
                [key: string]: unknown;
            }[];
            /** Runs */
            runs?: {
                [key: string]: unknown;
            }[];
            /**
             * Completed Cycles
             * @default 0
             */
            completed_cycles: number;
            /** Agent Runs */
            agent_runs?: {
                [key: string]: unknown;
            }[];
            /** Pipelines */
            pipelines?: {
                [key: string]: unknown;
            }[];
            /** Handoffs */
            handoffs?: {
                [key: string]: unknown;
            }[];
        };
        /** PasswordUpdate */
        PasswordUpdate: {
            /** Password */
            password: string;
            /** Current Password */
            current_password?: string | null;
        };
        /** PipelineCreate */
        PipelineCreate: {
            /** Expected Revision */
            expected_revision: number;
            /**
             * Template
             * @enum {string}
             */
            template: "first_evidence" | "pivot" | "learning" | "funding" | "complete";
            /** Objective */
            objective: string;
            /** Hypothesis Id */
            hypothesis_id: string;
        };
        /** Protocol */
        Protocol: {
            /** Intervention */
            intervention: string;
            /** Metric */
            metric: string;
            /** Threshold Percent */
            threshold_percent: number | string;
            /** Minimum N */
            minimum_n: number;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Stop Rule */
            stop_rule: string;
        };
        /** ProviderList */
        ProviderList: {
            /** Providers */
            providers: components["schemas"]["ProviderView"][];
        };
        /** ProviderView */
        ProviderView: {
            /**
             * Id
             * @enum {string}
             */
            id: "google" | "github";
            /** Label */
            label: string;
            /** Available */
            available: boolean;
            /**
             * Connected
             * @default false
             */
            connected: boolean;
            /** Email */
            email?: string | null;
        };
        /** ReceiptCreate */
        ReceiptCreate: {
            /** Expected Revision */
            expected_revision: number;
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Title */
            title: string;
            /**
             * Kind
             * @default source
             * @enum {string}
             */
            kind: "source" | "interview" | "observation";
            /** Content */
            content: string;
            /** Locator */
            locator: string;
            /**
             * Relation
             * @default contextualizes
             * @enum {string}
             */
            relation: "supports" | "contradicts" | "contextualizes";
            /** Limitations */
            limitations: string;
            /**
             * Consent
             * @enum {string}
             */
            consent: "public_source" | "notes_only" | "quote_permitted" | "private_observation";
            /** Participant Code */
            participant_code?: string | null;
            /**
             * Collected On
             * Format: date
             */
            collected_on: string;
        };
        /** Register */
        Register: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
        };
        /** RunCreate */
        RunCreate: {
            /** Expected Revision */
            expected_revision: number;
            /** Hypothesis Id */
            hypothesis_id: string;
            /**
             * Capability
             * @default research
             * @enum {string}
             */
            capability: "research" | "customer" | "model";
            /** Objective */
            objective: string;
            /** Evidence Ids */
            evidence_ids?: string[];
            /**
             * External Actions
             * @default false
             * @constant
             */
            external_actions: false;
            /**
             * Max Cost Inr
             * @default 0
             * @constant
             */
            max_cost_inr: 0;
        };
        /** SourceRead */
        SourceRead: {
            /** Url */
            url: string;
            /**
             * Approved
             * @constant
             */
            approved: true;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VentureCreate */
        VentureCreate: {
            /** Name */
            name: string;
            /** Idea */
            idea: string;
            /** Customer Segment */
            customer_segment: string;
            /** Geography */
            geography: string;
            /** First Hypothesis */
            first_hypothesis: string;
        };
        /** VentureList */
        VentureList: {
            /** Ventures */
            ventures: components["schemas"]["VentureView"][];
        };
        /** VentureView */
        VentureView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Idea */
            idea: string;
            /** Customer Segment */
            customer_segment: string;
            /** Geography */
            geography: string;
            /** Stage */
            stage: string;
            /** Revision */
            revision: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WebSearch */
        WebSearch: {
            /** Query */
            query: string;
            /**
             * Approved
             * @constant
             */
            approved: true;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FounderView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FounderView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_password_api_v1_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FounderView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    available_providers_api_v1_auth_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderList"];
                };
            };
        };
    };
    connections_api_v1_auth_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderList"];
                };
            };
        };
    };
    password_status_api_v1_auth_password_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    start_redirect_api_v1_auth_oauth__provider__start_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "google" | "github";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_v1_auth_oauth__provider__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "google" | "github";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthStart"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_api_v1_auth_oauth__provider__callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "google" | "github";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FounderView"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ventures_api_v1_ventures_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VentureList"];
                };
            };
        };
    };
    create_venture_api_v1_ventures_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VentureCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Passport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_passport_api_v1_ventures__venture_id__passport_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Passport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hypotheses_api_v1_ventures__venture_id__hypotheses_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HypothesisView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_hypothesis_api_v1_ventures__venture_id__hypotheses_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HypothesisCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Passport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    edit_concept_api_v1_ventures__venture_id__intake_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConceptUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_api_v1_ventures__venture_id__evidence_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_api_v1_ventures__venture_id__evidence__receipt_id__withdraw_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                venture_id: string;
                receipt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Command"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifact_api_v1_ventures__venture_id__artifacts_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_experiment_api_v1_ventures__venture_id__experiments_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observe_api_v1_ventures__venture_id__experiments__experiment_id__observations_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                venture_id: string;
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_v1_ventures__venture_id__decisions_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_api_v1_ventures__venture_id__runs_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agents_api_v1_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_pipeline_api_v1_ventures__venture_id__pipelines_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_api_v1_ventures__venture_id__agent_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_ventures__venture_id__agent_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venture_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_v1_ventures__venture_id__agent_runs__run_id__review_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                venture_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_ventures__venture_id__agent_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path: {
                venture_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Command"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_saved_api_v1_ventures__venture_id__research_sources_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_file_api_v1_ventures__venture_id__research_read_file_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileRead"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_source_api_v1_ventures__venture_id__research_read_source_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRead"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_web_api_v1_ventures__venture_id__research_web_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebSearch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_v1_ventures__venture_id__mvp_exports_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportSelection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_api_v1_ventures__venture_id__mvp_exports_download_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportApproval"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
