import { test, expect } from "@playwright/test";

test("thirteen tools, real negative result, founder decision and portable history", async ({ page }) => {
  test.setTimeout(120000);
  const errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  await page.goto("/");
  await page.getByLabel("Email address").fill("cycle-browser@test.local");
  await page.getByRole("button", { name: "Continue with email", exact: true }).click();
  await page.getByLabel("Password", { exact: true }).fill("browser-test-only-password");
  await page.getByRole("button", { name: "Enter your workspace" }).click();
  await page.getByLabel("Venture name").fill("Cohort Fieldnotes");
  await page.getByLabel("The idea", { exact: true }).fill("Preserve evidence and reviewed decisions for founders working with mentors.");
  await page.getByLabel("Who is it for?").fill("First-time founders");
  await page.getByLabel("Where will you begin?").fill("Bengaluru, India");
  await page.getByLabel("Your first hypothesis").fill("Founders will commit to a dated pilot meeting.");
  await page.getByRole("button", { name: "Create Venture Passport" }).click();
  await expect(page.getByRole("heading", { name: "Cohort Fieldnotes", exact: true })).toBeVisible();
  const nav = page.getByRole("navigation", { name: "Product workspace" });
  for (const label of ["Research Desk", "Market Lab", "Customer Lab", "Competitor Room", "Model Studio", "Finance Lab", "MVP and Experiment Lab", "Simulation Arena", "Founder Academy", "Ecosystem Hub", "Investor Room", "Venture Passport", "Mentor Home"]) {
    await nav.getByRole("button", { name: label, exact: true }).click();
    await expect(page.getByRole("heading", { name: label === "Mentor Home" ? "Make your next move count." : label, exact: true })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  }
  await page.screenshot({ path: ".local/evidence-home-desktop.png", fullPage: true });
  await nav.getByRole("button", { name: "MVP and Experiment Lab", exact: true }).click();
  await page.getByLabel("Experiment name").fill("Dated pilot commitment");
  await page.getByLabel("Intervention and recruitment plan").fill("Ask two founders to commit to a dated pilot meeting.");
  await page.getByLabel("Binary success metric").fill("Dated commitment");
  await page.getByLabel("Success threshold (%)").fill("50");
  await page.getByLabel("Minimum sample size").fill("2");
  await page.getByLabel("Stop rule", { exact: true }).fill("Stop at two interviews.");
  await page.getByRole("button", { name: "Approve and lock protocol" }).click();
  await expect(page.getByText("Protocol locked", { exact: true })).toBeVisible();
  for (let i = 1; i <= 2; i++) {
    await nav.getByRole("button", { name: "Customer Lab", exact: true }).click();
    await page.getByLabel("Receipt title").fill(`Interview P0${i}`);
    await page.getByLabel("Source URL, page or note locator").fill(`Interview P0${i} at 14:22`);
    await page.getByLabel("Observed behaviour or exact notes").fill("The founder discussed their workflow but declined a dated pilot meeting.");
    await page.getByLabel("Scope and limitations").fill("One interview, not purchase evidence.");
    await page.getByLabel("Participant code", { exact: true }).fill(`P0${i}`);
    await page.getByRole("button", { name: "Save evidence receipt" }).click();
    await expect(page.getByRole("heading", { name: `Interview P0${i}`, exact: true })).toBeVisible();
    await nav.getByRole("button", { name: "MVP and Experiment Lab", exact: true }).click();
    await page.getByLabel("Participant code", { exact: true }).fill(`P0${i}`);
    await page.getByLabel("Observation receipt").selectOption({ label: `Interview P0${i} · P0${i}` });
    await page.getByRole("button", { name: "Record observation", exact: true }).click();
    await expect(page.getByText(`0 successes / ${i} valid observations`, { exact: true })).toBeVisible();
  }
  await expect(page.getByText("THRESHOLD NOT MET", { exact: true })).toBeVisible();
  await page.getByRole("combobox", { name: "Decision", exact: true }).selectOption("revise");
  await page.getByLabel("Rationale and next commitment").fill("The dated pilot offer failed. Revise the value proposition before testing again.");
  await page.getByRole("button", { name: "Record founder decision" }).click();
  await expect(page.getByRole("button", { name: "Record founder decision" })).toHaveCount(0);
  await page.screenshot({ path: ".local/locked-experiment-desktop.png", fullPage: true });
  await nav.getByRole("button", { name: "Research Desk", exact: true }).click();
  await page.getByLabel("Your decision question").fill("What customer observations challenge our current pilot offer?");
  await page.getByRole("button", { name: "Start evidence review" }).click();
  await expect(page.getByText("AWAITING REVIEW", { exact: true })).toBeVisible({ timeout: 15000 });
  await nav.getByRole("button", { name: "Finance Lab", exact: true }).click();
  await page.getByLabel("Scenario name").fill("Cohort economics");
  await page.getByLabel("Price per unit (INR)").fill("120000");
  await page.getByLabel("Units sold").fill("1");
  await page.getByLabel("Total direct delivery cost (INR)").fill("50000");
  await page.getByLabel("Fixed cost (INR)").fill("100000");
  await page.getByLabel("Cash actually collected (INR)").fill("0");
  await page.getByLabel("Starting cash balance (INR)").fill("300000");
  await page.getByLabel("Acquisition spend (INR, optional)", { exact: true }).fill("30000");
  await page.getByLabel("New paying customers (optional)", { exact: true }).fill("3");
  await page.getByLabel("Average customer revenue per period (INR, optional)", { exact: true }).fill("20000");
  await page.getByLabel("Customer lifetime periods (optional)", { exact: true }).fill("3");
  await page.getByRole("button", { name: "Calculate and save proposal" }).click();
  await expect(page.getByText("58.33", { exact: true })).toBeVisible();
  await expect(page.getByText("10000.00", { exact: true })).toBeVisible();
  await expect(page.getByText("60000.00", { exact: true })).toBeVisible();
  await expect(page.getByText("35000.00", { exact: true })).toBeVisible();
  await page.screenshot({ path: ".local/finance-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: ".local/finance-mobile.png", fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1080 });
  await nav.getByRole("button", { name: "Venture Passport", exact: true }).click();
  await expect(page.getByText("The dated pilot offer failed. Revise the value proposition before testing again.", { exact: true })).toBeVisible();
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export JSON" }).click();
  expect((await downloadPromise).suggestedFilename()).toBe("venture-passport.json");
  await page.reload();
  await expect(page.getByText("1 evidence-to-decision cycles", { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await nav.getByRole("button", { name: "Customer Lab", exact: true }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: ".local/customer-mobile.png", fullPage: true });
  expect(errors).toEqual([]);
});
