import { test, expect } from "@playwright/test";

test("founder signs in, creates a Passport, captures hypotheses and reloads", async ({ page }) => {
  test.setTimeout(120000);
  const browserErrors: string[] = [];
  page.on("pageerror", error => browserErrors.push(error.message));
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Welcome to the Forge." })).toBeVisible();
  await page.screenshot({ path: ".local/sign-in-desktop.png", fullPage: true, animations: "disabled" });
  await page.getByLabel("Email address").fill("invalid-email");
  await page.getByRole("button", { name: "Continue with email", exact: true }).click();
  await expect(page.getByLabel("Password", { exact: true })).toHaveCount(0);
  await page.getByLabel("Email address").fill("browser@test.local");
  await page.getByLabel("Email address").press("Enter");
  await expect(page.getByLabel("Password", { exact: true })).toBeFocused();
  await page.getByLabel("Password", { exact: true }).fill("discard-this-password");
  await page.getByRole("button", { name: "Show password", exact: true }).click();
  await expect(page.getByLabel("Password", { exact: true })).toHaveAttribute("type", "text");
  await page.getByRole("button", { name: "Use a different email" }).click();
  await expect(page.getByLabel("Email address")).toBeFocused();
  await page.getByRole("button", { name: "Continue with email", exact: true }).click();
  await expect(page.getByLabel("Password", { exact: true })).toHaveValue("");
  await expect(page.getByLabel("Password", { exact: true })).toHaveAttribute("type", "password");
  await page.getByLabel("Password", { exact: true }).fill("wrong-password");
  const rejectedLogin = page.waitForResponse(response => response.url().endsWith("/api/v1/auth/login") && response.request().method() === "POST");
  await page.getByRole("button", { name: "Enter your workspace" }).click();
  expect((await rejectedLogin).status()).toBe(401);
  await expect(page.getByRole("alert").filter({ hasText: "incorrect" })).toBeVisible();
  let releaseLogin!: () => void;
  let pendingLogins = 0;
  const loginGate = new Promise<void>(resolve => { releaseLogin = resolve; });
  await page.route("**/api/v1/auth/login", async route => {
    pendingLogins += 1;
    await loginGate;
    await route.continue();
  });
  await page.getByLabel("Password", { exact: true }).fill("browser-test-only-password");
  await page.getByRole("button", { name: "Enter your workspace" }).click();
  await expect(page.getByRole("button", { name: "Signing in…", exact: true })).toBeDisabled();
  await expect(page.getByRole("status")).toHaveText("Checking your credentials securely…");
  await expect(page.getByLabel("Email address")).toBeDisabled();
  await expect(page.getByLabel("Password", { exact: true })).toBeDisabled();
  await page.keyboard.press("Enter");
  expect(pendingLogins).toBe(1);
  const acceptedLogin = page.waitForResponse(response => response.url().endsWith("/api/v1/auth/login") && response.request().method() === "POST");
  releaseLogin();
  expect((await acceptedLogin).status()).toBe(200);
  await expect(page.getByRole("heading", { name: "Give your idea a place to grow." })).toBeVisible();
  await page.unroute("**/api/v1/auth/login");
  await page.getByRole("button", { name: "Account settings", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Account settings" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Connect Google", exact: true })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Connect GitHub", exact: true })).toBeDisabled();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog", { name: "Account settings" })).not.toBeVisible();
  await page.screenshot({ path: ".local/onboarding-desktop.png", fullPage: true });
  await page.getByLabel("Venture name").fill("Founders Fieldnotes");
  await page.getByLabel("The idea", { exact: true }).fill("Help first-time founders learn from customer conversations before building their product.");
  await page.getByLabel("Who is it for?").fill("First-time founders in Bengaluru");
  await page.getByLabel("Where will you begin?").fill("Bengaluru, India");
  await page.getByLabel("Your first hypothesis").fill("First-time founders struggle to find five people willing to discuss their problem.");
  await page.getByRole("button", { name: "Create Venture Passport" }).click();
  await expect(page.getByRole("heading", { name: "Founders Fieldnotes", exact: true })).toBeVisible();
  await expect(page.getByText("Unvalidated", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Add hypothesis", exact: true }).click();
  await page.getByLabel("Hypothesis", { exact: true }).fill("Founders will pay INR 499 for a structured customer interview workflow.");
  await page.getByLabel("Category").selectOption("pricing");
  await page.getByRole("button", { name: "Save hypothesis" }).click();
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await expect(page.getByText("Unvalidated", { exact: true })).toHaveCount(2);
  await page.screenshot({ path: ".local/mentor-home-desktop.png", fullPage: true });
  await page.getByRole("button", { name: "Venture Passport", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Venture Passport", exact: true })).toBeVisible();
  await expect(page.getByText("Revision 2", { exact: true })).toBeVisible();
  const downloadEvent = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export JSON" }).click();
  expect((await downloadEvent).suggestedFilename()).toBe("venture-passport.json");
  await page.reload();
  await expect(page.getByRole("heading", { name: "Founders Fieldnotes", exact: true })).toBeVisible();
  await expect(page.getByText("Unvalidated", { exact: true })).toHaveCount(2);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: ".local/mentor-home-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole("link", { name: /Company OS/ }).click();
  await expect(page.getByText("Planned · no company agents active")).toBeVisible();
  await page.getByRole("link", { name: /Return to your founder workspace/ }).click();
  await expect(page.getByRole("heading", { name: "Founders Fieldnotes", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Sign out" }).click();
  await expect(page.getByRole("heading", { name: "Welcome to the Forge." })).toBeVisible();
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.screenshot({ path: ".local/sign-in-mobile.png", fullPage: true, animations: "disabled" });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByLabel("Email address").fill("browser@test.local");
  await page.getByRole("button", { name: "Continue to password", exact: true }).click();
  await page.screenshot({ path: ".local/sign-in-password-mobile.png", fullPage: true, animations: "disabled" });
  await page.getByLabel("Password", { exact: true }).fill("browser-test-only-password");
  await page.getByLabel("Password", { exact: true }).press("Enter");
  await expect(page.getByRole("heading", { name: "Founders Fieldnotes", exact: true })).toBeVisible();
  expect(browserErrors).toEqual([]);
});
