import { test, expect } from "@playwright/test";

test("a public email user registers, keeps their Passport, and changes their password", async ({ page }) => {
  test.setTimeout(120000);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await page.getByLabel("Email address").fill("public-browser@example.com");
  await page.getByRole("button", { name: "Continue with email", exact: true }).click();
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  await expect(page.getByLabel("Your name")).toBeFocused();
  await page.getByLabel("Your name").fill("Public Founder");
  await page.getByLabel("Password", { exact: true }).fill("public founder test passphrase");
  await page.screenshot({ path: ".local/public-register-desktop.png", fullPage: true, animations: "disabled" });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: ".local/public-register-mobile.png", fullPage: true, animations: "disabled" });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const registered = page.waitForResponse(response => response.url().endsWith("/api/v1/auth/register") && response.request().method() === "POST");
  await page.getByRole("button", { name: "Create your account", exact: true }).click();
  expect((await registered).status()).toBe(201);
  await expect(page.getByRole("heading", { name: "Give your idea a place to grow." })).toBeVisible();
  await page.getByLabel("Venture name").fill("Public Venture");
  await page.getByLabel("The idea", { exact: true }).fill("Help new founders learn through structured customer conversations.");
  await page.getByLabel("Who is it for?").fill("First-time founders");
  await page.getByLabel("Where will you begin?").fill("India");
  await page.getByLabel("Your first hypothesis").fill("New founders need help planning and reviewing their first interviews.");
  await page.getByRole("button", { name: "Create Venture Passport" }).click();
  await expect(page.getByRole("heading", { name: "Public Venture", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Account settings", exact: true }).click();
  const account = page.getByRole("dialog", { name: "Account settings" });
  await account.getByText("Change password", { exact: true }).click();
  await account.getByLabel("Current password").fill("public founder test passphrase");
  await account.getByLabel("New password").fill("a changed public founder passphrase");
  const changed = page.waitForResponse(response => response.url().endsWith("/api/v1/auth/password") && response.request().method() === "POST");
  await account.getByRole("button", { name: "Save password", exact: true }).click();
  expect((await changed).status()).toBe(200);
  await expect(account.getByRole("status")).toHaveText("Password saved. Your other sessions have been signed out.");
  await account.getByRole("button", { name: "Close account settings" }).click();
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await page.getByLabel("Email address").fill("public-browser@example.com");
  await page.getByRole("button", { name: "Continue with email", exact: true }).click();
  await page.getByLabel("Password", { exact: true }).fill("a changed public founder passphrase");
  const loggedIn = page.waitForResponse(response => response.url().endsWith("/api/v1/auth/login") && response.request().method() === "POST");
  await page.getByRole("button", { name: "Enter your workspace", exact: true }).click();
  expect((await loggedIn).status()).toBe(200);
  await expect(page.getByRole("heading", { name: "Public Venture", exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("heading", { name: "Public Venture", exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
